// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.router.command;

/**
 * Protobuf type {@code xray.app.router.command.BalancerMsg}
 */
public final class BalancerMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.app.router.command.BalancerMsg)
    BalancerMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BalancerMsg.newBuilder() to construct.
  private BalancerMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BalancerMsg() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BalancerMsg();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xray.app.router.command.Command.internal_static_xray_app_router_command_BalancerMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xray.app.router.command.Command.internal_static_xray_app_router_command_BalancerMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xray.app.router.command.BalancerMsg.class, com.xray.app.router.command.BalancerMsg.Builder.class);
  }

  private int bitField0_;
  public static final int OVERRIDE_FIELD_NUMBER = 5;
  private com.xray.app.router.command.OverrideInfo override_;
  /**
   * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
   * @return Whether the override field is set.
   */
  @java.lang.Override
  public boolean hasOverride() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
   * @return The override.
   */
  @java.lang.Override
  public com.xray.app.router.command.OverrideInfo getOverride() {
    return override_ == null ? com.xray.app.router.command.OverrideInfo.getDefaultInstance() : override_;
  }
  /**
   * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
   */
  @java.lang.Override
  public com.xray.app.router.command.OverrideInfoOrBuilder getOverrideOrBuilder() {
    return override_ == null ? com.xray.app.router.command.OverrideInfo.getDefaultInstance() : override_;
  }

  public static final int PRINCIPLE_TARGET_FIELD_NUMBER = 6;
  private com.xray.app.router.command.PrincipleTargetInfo principleTarget_;
  /**
   * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
   * @return Whether the principleTarget field is set.
   */
  @java.lang.Override
  public boolean hasPrincipleTarget() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
   * @return The principleTarget.
   */
  @java.lang.Override
  public com.xray.app.router.command.PrincipleTargetInfo getPrincipleTarget() {
    return principleTarget_ == null ? com.xray.app.router.command.PrincipleTargetInfo.getDefaultInstance() : principleTarget_;
  }
  /**
   * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
   */
  @java.lang.Override
  public com.xray.app.router.command.PrincipleTargetInfoOrBuilder getPrincipleTargetOrBuilder() {
    return principleTarget_ == null ? com.xray.app.router.command.PrincipleTargetInfo.getDefaultInstance() : principleTarget_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getOverride());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getPrincipleTarget());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getOverride());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getPrincipleTarget());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xray.app.router.command.BalancerMsg)) {
      return super.equals(obj);
    }
    com.xray.app.router.command.BalancerMsg other = (com.xray.app.router.command.BalancerMsg) obj;

    if (hasOverride() != other.hasOverride()) return false;
    if (hasOverride()) {
      if (!getOverride()
          .equals(other.getOverride())) return false;
    }
    if (hasPrincipleTarget() != other.hasPrincipleTarget()) return false;
    if (hasPrincipleTarget()) {
      if (!getPrincipleTarget()
          .equals(other.getPrincipleTarget())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOverride()) {
      hash = (37 * hash) + OVERRIDE_FIELD_NUMBER;
      hash = (53 * hash) + getOverride().hashCode();
    }
    if (hasPrincipleTarget()) {
      hash = (37 * hash) + PRINCIPLE_TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getPrincipleTarget().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xray.app.router.command.BalancerMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xray.app.router.command.BalancerMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xray.app.router.command.BalancerMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.router.command.BalancerMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xray.app.router.command.BalancerMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.app.router.command.BalancerMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.app.router.command.BalancerMsg)
      com.xray.app.router.command.BalancerMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xray.app.router.command.Command.internal_static_xray_app_router_command_BalancerMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xray.app.router.command.Command.internal_static_xray_app_router_command_BalancerMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xray.app.router.command.BalancerMsg.class, com.xray.app.router.command.BalancerMsg.Builder.class);
    }

    // Construct using com.xray.app.router.command.BalancerMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOverrideFieldBuilder();
        getPrincipleTargetFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      override_ = null;
      if (overrideBuilder_ != null) {
        overrideBuilder_.dispose();
        overrideBuilder_ = null;
      }
      principleTarget_ = null;
      if (principleTargetBuilder_ != null) {
        principleTargetBuilder_.dispose();
        principleTargetBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xray.app.router.command.Command.internal_static_xray_app_router_command_BalancerMsg_descriptor;
    }

    @java.lang.Override
    public com.xray.app.router.command.BalancerMsg getDefaultInstanceForType() {
      return com.xray.app.router.command.BalancerMsg.getDefaultInstance();
    }

    @java.lang.Override
    public com.xray.app.router.command.BalancerMsg build() {
      com.xray.app.router.command.BalancerMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xray.app.router.command.BalancerMsg buildPartial() {
      com.xray.app.router.command.BalancerMsg result = new com.xray.app.router.command.BalancerMsg(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xray.app.router.command.BalancerMsg result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.override_ = overrideBuilder_ == null
            ? override_
            : overrideBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.principleTarget_ = principleTargetBuilder_ == null
            ? principleTarget_
            : principleTargetBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xray.app.router.command.BalancerMsg) {
        return mergeFrom((com.xray.app.router.command.BalancerMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xray.app.router.command.BalancerMsg other) {
      if (other == com.xray.app.router.command.BalancerMsg.getDefaultInstance()) return this;
      if (other.hasOverride()) {
        mergeOverride(other.getOverride());
      }
      if (other.hasPrincipleTarget()) {
        mergePrincipleTarget(other.getPrincipleTarget());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 42: {
              input.readMessage(
                  getOverrideFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getPrincipleTargetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.xray.app.router.command.OverrideInfo override_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.app.router.command.OverrideInfo, com.xray.app.router.command.OverrideInfo.Builder, com.xray.app.router.command.OverrideInfoOrBuilder> overrideBuilder_;
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     * @return Whether the override field is set.
     */
    public boolean hasOverride() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     * @return The override.
     */
    public com.xray.app.router.command.OverrideInfo getOverride() {
      if (overrideBuilder_ == null) {
        return override_ == null ? com.xray.app.router.command.OverrideInfo.getDefaultInstance() : override_;
      } else {
        return overrideBuilder_.getMessage();
      }
    }
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     */
    public Builder setOverride(com.xray.app.router.command.OverrideInfo value) {
      if (overrideBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        override_ = value;
      } else {
        overrideBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     */
    public Builder setOverride(
        com.xray.app.router.command.OverrideInfo.Builder builderForValue) {
      if (overrideBuilder_ == null) {
        override_ = builderForValue.build();
      } else {
        overrideBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     */
    public Builder mergeOverride(com.xray.app.router.command.OverrideInfo value) {
      if (overrideBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          override_ != null &&
          override_ != com.xray.app.router.command.OverrideInfo.getDefaultInstance()) {
          getOverrideBuilder().mergeFrom(value);
        } else {
          override_ = value;
        }
      } else {
        overrideBuilder_.mergeFrom(value);
      }
      if (override_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     */
    public Builder clearOverride() {
      bitField0_ = (bitField0_ & ~0x00000001);
      override_ = null;
      if (overrideBuilder_ != null) {
        overrideBuilder_.dispose();
        overrideBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     */
    public com.xray.app.router.command.OverrideInfo.Builder getOverrideBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getOverrideFieldBuilder().getBuilder();
    }
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     */
    public com.xray.app.router.command.OverrideInfoOrBuilder getOverrideOrBuilder() {
      if (overrideBuilder_ != null) {
        return overrideBuilder_.getMessageOrBuilder();
      } else {
        return override_ == null ?
            com.xray.app.router.command.OverrideInfo.getDefaultInstance() : override_;
      }
    }
    /**
     * <code>.xray.app.router.command.OverrideInfo override = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.app.router.command.OverrideInfo, com.xray.app.router.command.OverrideInfo.Builder, com.xray.app.router.command.OverrideInfoOrBuilder> 
        getOverrideFieldBuilder() {
      if (overrideBuilder_ == null) {
        overrideBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xray.app.router.command.OverrideInfo, com.xray.app.router.command.OverrideInfo.Builder, com.xray.app.router.command.OverrideInfoOrBuilder>(
                getOverride(),
                getParentForChildren(),
                isClean());
        override_ = null;
      }
      return overrideBuilder_;
    }

    private com.xray.app.router.command.PrincipleTargetInfo principleTarget_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.app.router.command.PrincipleTargetInfo, com.xray.app.router.command.PrincipleTargetInfo.Builder, com.xray.app.router.command.PrincipleTargetInfoOrBuilder> principleTargetBuilder_;
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     * @return Whether the principleTarget field is set.
     */
    public boolean hasPrincipleTarget() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     * @return The principleTarget.
     */
    public com.xray.app.router.command.PrincipleTargetInfo getPrincipleTarget() {
      if (principleTargetBuilder_ == null) {
        return principleTarget_ == null ? com.xray.app.router.command.PrincipleTargetInfo.getDefaultInstance() : principleTarget_;
      } else {
        return principleTargetBuilder_.getMessage();
      }
    }
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     */
    public Builder setPrincipleTarget(com.xray.app.router.command.PrincipleTargetInfo value) {
      if (principleTargetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        principleTarget_ = value;
      } else {
        principleTargetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     */
    public Builder setPrincipleTarget(
        com.xray.app.router.command.PrincipleTargetInfo.Builder builderForValue) {
      if (principleTargetBuilder_ == null) {
        principleTarget_ = builderForValue.build();
      } else {
        principleTargetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     */
    public Builder mergePrincipleTarget(com.xray.app.router.command.PrincipleTargetInfo value) {
      if (principleTargetBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          principleTarget_ != null &&
          principleTarget_ != com.xray.app.router.command.PrincipleTargetInfo.getDefaultInstance()) {
          getPrincipleTargetBuilder().mergeFrom(value);
        } else {
          principleTarget_ = value;
        }
      } else {
        principleTargetBuilder_.mergeFrom(value);
      }
      if (principleTarget_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     */
    public Builder clearPrincipleTarget() {
      bitField0_ = (bitField0_ & ~0x00000002);
      principleTarget_ = null;
      if (principleTargetBuilder_ != null) {
        principleTargetBuilder_.dispose();
        principleTargetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     */
    public com.xray.app.router.command.PrincipleTargetInfo.Builder getPrincipleTargetBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPrincipleTargetFieldBuilder().getBuilder();
    }
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     */
    public com.xray.app.router.command.PrincipleTargetInfoOrBuilder getPrincipleTargetOrBuilder() {
      if (principleTargetBuilder_ != null) {
        return principleTargetBuilder_.getMessageOrBuilder();
      } else {
        return principleTarget_ == null ?
            com.xray.app.router.command.PrincipleTargetInfo.getDefaultInstance() : principleTarget_;
      }
    }
    /**
     * <code>.xray.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.app.router.command.PrincipleTargetInfo, com.xray.app.router.command.PrincipleTargetInfo.Builder, com.xray.app.router.command.PrincipleTargetInfoOrBuilder> 
        getPrincipleTargetFieldBuilder() {
      if (principleTargetBuilder_ == null) {
        principleTargetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xray.app.router.command.PrincipleTargetInfo, com.xray.app.router.command.PrincipleTargetInfo.Builder, com.xray.app.router.command.PrincipleTargetInfoOrBuilder>(
                getPrincipleTarget(),
                getParentForChildren(),
                isClean());
        principleTarget_ = null;
      }
      return principleTargetBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.app.router.command.BalancerMsg)
  }

  // @@protoc_insertion_point(class_scope:xray.app.router.command.BalancerMsg)
  private static final com.xray.app.router.command.BalancerMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xray.app.router.command.BalancerMsg();
  }

  public static com.xray.app.router.command.BalancerMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BalancerMsg>
      PARSER = new com.google.protobuf.AbstractParser<BalancerMsg>() {
    @java.lang.Override
    public BalancerMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BalancerMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BalancerMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xray.app.router.command.BalancerMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

