// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.router.command;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_RoutingContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_RoutingContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_RoutingContext_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_RoutingContext_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_TestRouteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_TestRouteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_PrincipleTargetInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_PrincipleTargetInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_OverrideInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_OverrideInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_BalancerMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_BalancerMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_GetBalancerInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_GetBalancerInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_GetBalancerInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_GetBalancerInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_OverrideBalancerTargetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_OverrideBalancerTargetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_OverrideBalancerTargetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_OverrideBalancerTargetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_AddRuleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_AddRuleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_AddRuleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_AddRuleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_RemoveRuleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_RemoveRuleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_RemoveRuleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_RemoveRuleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_ListRuleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_ListRuleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_ListRuleItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_ListRuleItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_ListRuleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_ListRuleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n app/router/command/command.proto\022\027xray" +
      ".app.router.command\032\030common/net/network." +
      "proto\032!common/serial/typed_message.proto" +
      "\"\274\003\n\016RoutingContext\022\022\n\nInboundTag\030\001 \001(\t\022" +
      ")\n\007Network\030\002 \001(\0162\030.xray.common.net.Netwo" +
      "rk\022\021\n\tSourceIPs\030\003 \003(\014\022\021\n\tTargetIPs\030\004 \003(\014" +
      "\022\022\n\nSourcePort\030\005 \001(\r\022\022\n\nTargetPort\030\006 \001(\r" +
      "\022\024\n\014TargetDomain\030\007 \001(\t\022\020\n\010Protocol\030\010 \001(\t" +
      "\022\014\n\004User\030\t \001(\t\022K\n\nAttributes\030\n \003(\01327.xra" +
      "y.app.router.command.RoutingContext.Attr" +
      "ibutesEntry\022\031\n\021OutboundGroupTags\030\013 \003(\t\022\023" +
      "\n\013OutboundTag\030\014 \001(\t\022\020\n\010LocalIPs\030\r \003(\014\022\021\n" +
      "\tLocalPort\030\016 \001(\r\022\022\n\nVlessRoute\030\017 \001(\r\0321\n\017" +
      "AttributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"6\n\034SubscribeRoutingStatsRequest\022" +
      "\026\n\016FieldSelectors\030\001 \003(\t\"\202\001\n\020TestRouteReq" +
      "uest\022?\n\016RoutingContext\030\001 \001(\0132\'.xray.app." +
      "router.command.RoutingContext\022\026\n\016FieldSe" +
      "lectors\030\002 \003(\t\022\025\n\rPublishResult\030\003 \001(\010\"\"\n\023" +
      "PrincipleTargetInfo\022\013\n\003tag\030\001 \003(\t\"\036\n\014Over" +
      "rideInfo\022\016\n\006target\030\002 \001(\t\"\216\001\n\013BalancerMsg" +
      "\0227\n\010override\030\005 \001(\0132%.xray.app.router.com" +
      "mand.OverrideInfo\022F\n\020principle_target\030\006 " +
      "\001(\0132,.xray.app.router.command.PrincipleT" +
      "argetInfo\"%\n\026GetBalancerInfoRequest\022\013\n\003t" +
      "ag\030\001 \001(\t\"Q\n\027GetBalancerInfoResponse\0226\n\010b" +
      "alancer\030\001 \001(\0132$.xray.app.router.command." +
      "BalancerMsg\"D\n\035OverrideBalancerTargetReq" +
      "uest\022\023\n\013balancerTag\030\001 \001(\t\022\016\n\006target\030\002 \001(" +
      "\t\" \n\036OverrideBalancerTargetResponse\"X\n\016A" +
      "ddRuleRequest\0220\n\006config\030\001 \001(\0132 .xray.com" +
      "mon.serial.TypedMessage\022\024\n\014shouldAppend\030" +
      "\002 \001(\010\"\021\n\017AddRuleResponse\"$\n\021RemoveRuleRe" +
      "quest\022\017\n\007ruleTag\030\001 \001(\t\"\024\n\022RemoveRuleResp" +
      "onse\"\021\n\017ListRuleRequest\",\n\014ListRuleItem\022" +
      "\013\n\003tag\030\001 \001(\t\022\017\n\007ruleTag\030\002 \001(\t\"H\n\020ListRul" +
      "eResponse\0224\n\005rules\030\001 \003(\0132%.xray.app.rout" +
      "er.command.ListRuleItem\"\010\n\006Config2\242\006\n\016Ro" +
      "utingService\022{\n\025SubscribeRoutingStats\0225." +
      "xray.app.router.command.SubscribeRouting" +
      "StatsRequest\032\'.xray.app.router.command.R" +
      "outingContext\"\0000\001\022a\n\tTestRoute\022).xray.ap" +
      "p.router.command.TestRouteRequest\032\'.xray" +
      ".app.router.command.RoutingContext\"\000\022v\n\017" +
      "GetBalancerInfo\022/.xray.app.router.comman" +
      "d.GetBalancerInfoRequest\0320.xray.app.rout" +
      "er.command.GetBalancerInfoResponse\"\000\022\213\001\n" +
      "\026OverrideBalancerTarget\0226.xray.app.route" +
      "r.command.OverrideBalancerTargetRequest\032" +
      "7.xray.app.router.command.OverrideBalanc" +
      "erTargetResponse\"\000\022^\n\007AddRule\022\'.xray.app" +
      ".router.command.AddRuleRequest\032(.xray.ap" +
      "p.router.command.AddRuleResponse\"\000\022g\n\nRe" +
      "moveRule\022*.xray.app.router.command.Remov" +
      "eRuleRequest\032+.xray.app.router.command.R" +
      "emoveRuleResponse\"\000\022a\n\010ListRule\022(.xray.a" +
      "pp.router.command.ListRuleRequest\032).xray" +
      ".app.router.command.ListRuleResponse\"\000Bg" +
      "\n\033com.xray.app.router.commandP\001Z,github." +
      "com/xtls/xray-core/app/router/command\252\002\027" +
      "Xray.App.Router.Commandb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xray.common.net.NetworkOuterClass.getDescriptor(),
          com.xray.common.serial.TypedMessageOuterClass.getDescriptor(),
        });
    internal_static_xray_app_router_command_RoutingContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_app_router_command_RoutingContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_RoutingContext_descriptor,
        new java.lang.String[] { "InboundTag", "Network", "SourceIPs", "TargetIPs", "SourcePort", "TargetPort", "TargetDomain", "Protocol", "User", "Attributes", "OutboundGroupTags", "OutboundTag", "LocalIPs", "LocalPort", "VlessRoute", });
    internal_static_xray_app_router_command_RoutingContext_AttributesEntry_descriptor =
      internal_static_xray_app_router_command_RoutingContext_descriptor.getNestedTypes().get(0);
    internal_static_xray_app_router_command_RoutingContext_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_RoutingContext_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_descriptor,
        new java.lang.String[] { "FieldSelectors", });
    internal_static_xray_app_router_command_TestRouteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_xray_app_router_command_TestRouteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_TestRouteRequest_descriptor,
        new java.lang.String[] { "RoutingContext", "FieldSelectors", "PublishResult", });
    internal_static_xray_app_router_command_PrincipleTargetInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_xray_app_router_command_PrincipleTargetInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_PrincipleTargetInfo_descriptor,
        new java.lang.String[] { "Tag", });
    internal_static_xray_app_router_command_OverrideInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_xray_app_router_command_OverrideInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_OverrideInfo_descriptor,
        new java.lang.String[] { "Target", });
    internal_static_xray_app_router_command_BalancerMsg_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_xray_app_router_command_BalancerMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_BalancerMsg_descriptor,
        new java.lang.String[] { "Override", "PrincipleTarget", });
    internal_static_xray_app_router_command_GetBalancerInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_xray_app_router_command_GetBalancerInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_GetBalancerInfoRequest_descriptor,
        new java.lang.String[] { "Tag", });
    internal_static_xray_app_router_command_GetBalancerInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_xray_app_router_command_GetBalancerInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_GetBalancerInfoResponse_descriptor,
        new java.lang.String[] { "Balancer", });
    internal_static_xray_app_router_command_OverrideBalancerTargetRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_xray_app_router_command_OverrideBalancerTargetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_OverrideBalancerTargetRequest_descriptor,
        new java.lang.String[] { "BalancerTag", "Target", });
    internal_static_xray_app_router_command_OverrideBalancerTargetResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_xray_app_router_command_OverrideBalancerTargetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_OverrideBalancerTargetResponse_descriptor,
        new java.lang.String[] { });
    internal_static_xray_app_router_command_AddRuleRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_xray_app_router_command_AddRuleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_AddRuleRequest_descriptor,
        new java.lang.String[] { "Config", "ShouldAppend", });
    internal_static_xray_app_router_command_AddRuleResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_xray_app_router_command_AddRuleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_AddRuleResponse_descriptor,
        new java.lang.String[] { });
    internal_static_xray_app_router_command_RemoveRuleRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_xray_app_router_command_RemoveRuleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_RemoveRuleRequest_descriptor,
        new java.lang.String[] { "RuleTag", });
    internal_static_xray_app_router_command_RemoveRuleResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_xray_app_router_command_RemoveRuleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_RemoveRuleResponse_descriptor,
        new java.lang.String[] { });
    internal_static_xray_app_router_command_ListRuleRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_xray_app_router_command_ListRuleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_ListRuleRequest_descriptor,
        new java.lang.String[] { });
    internal_static_xray_app_router_command_ListRuleItem_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_xray_app_router_command_ListRuleItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_ListRuleItem_descriptor,
        new java.lang.String[] { "Tag", "RuleTag", });
    internal_static_xray_app_router_command_ListRuleResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_xray_app_router_command_ListRuleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_ListRuleResponse_descriptor,
        new java.lang.String[] { "Rules", });
    internal_static_xray_app_router_command_Config_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_xray_app_router_command_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_Config_descriptor,
        new java.lang.String[] { });
    com.xray.common.net.NetworkOuterClass.getDescriptor();
    com.xray.common.serial.TypedMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
