// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.router.command;

public interface ListRuleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.command.ListRuleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xray.app.router.command.ListRuleItem rules = 1;</code>
   */
  java.util.List<com.xray.app.router.command.ListRuleItem> 
      getRulesList();
  /**
   * <code>repeated .xray.app.router.command.ListRuleItem rules = 1;</code>
   */
  com.xray.app.router.command.ListRuleItem getRules(int index);
  /**
   * <code>repeated .xray.app.router.command.ListRuleItem rules = 1;</code>
   */
  int getRulesCount();
  /**
   * <code>repeated .xray.app.router.command.ListRuleItem rules = 1;</code>
   */
  java.util.List<? extends com.xray.app.router.command.ListRuleItemOrBuilder> 
      getRulesOrBuilderList();
  /**
   * <code>repeated .xray.app.router.command.ListRuleItem rules = 1;</code>
   */
  com.xray.app.router.command.ListRuleItemOrBuilder getRulesOrBuilder(
      int index);
}
