// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.router.command;

public interface ListRuleItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.command.ListRuleItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>string ruleTag = 2;</code>
   * @return The ruleTag.
   */
  java.lang.String getRuleTag();
  /**
   * <code>string ruleTag = 2;</code>
   * @return The bytes for ruleTag.
   */
  com.google.protobuf.ByteString
      getRuleTagBytes();
}
