// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.router.command;

public interface ListRuleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.command.ListRuleRequest)
    com.google.protobuf.MessageOrBuilder {
}
