// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.router.command;

/**
 * Protobuf type {@code xray.app.router.command.PrincipleTargetInfo}
 */
public final class PrincipleTargetInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.app.router.command.PrincipleTargetInfo)
    PrincipleTargetInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PrincipleTargetInfo.newBuilder() to construct.
  private PrincipleTargetInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PrincipleTargetInfo() {
    tag_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PrincipleTargetInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xray.app.router.command.Command.internal_static_xray_app_router_command_PrincipleTargetInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xray.app.router.command.Command.internal_static_xray_app_router_command_PrincipleTargetInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xray.app.router.command.PrincipleTargetInfo.class, com.xray.app.router.command.PrincipleTargetInfo.Builder.class);
  }

  public static final int TAG_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tag_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string tag = 1;</code>
   * @return A list containing the tag.
   */
  public com.google.protobuf.ProtocolStringList
      getTagList() {
    return tag_;
  }
  /**
   * <code>repeated string tag = 1;</code>
   * @return The count of tag.
   */
  public int getTagCount() {
    return tag_.size();
  }
  /**
   * <code>repeated string tag = 1;</code>
   * @param index The index of the element to return.
   * @return The tag at the given index.
   */
  public java.lang.String getTag(int index) {
    return tag_.get(index);
  }
  /**
   * <code>repeated string tag = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tag at the given index.
   */
  public com.google.protobuf.ByteString
      getTagBytes(int index) {
    return tag_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tag_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tag_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < tag_.size(); i++) {
        dataSize += computeStringSizeNoTag(tag_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xray.app.router.command.PrincipleTargetInfo)) {
      return super.equals(obj);
    }
    com.xray.app.router.command.PrincipleTargetInfo other = (com.xray.app.router.command.PrincipleTargetInfo) obj;

    if (!getTagList()
        .equals(other.getTagList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTagCount() > 0) {
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTagList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xray.app.router.command.PrincipleTargetInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xray.app.router.command.PrincipleTargetInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.router.command.PrincipleTargetInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xray.app.router.command.PrincipleTargetInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.app.router.command.PrincipleTargetInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.app.router.command.PrincipleTargetInfo)
      com.xray.app.router.command.PrincipleTargetInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xray.app.router.command.Command.internal_static_xray_app_router_command_PrincipleTargetInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xray.app.router.command.Command.internal_static_xray_app_router_command_PrincipleTargetInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xray.app.router.command.PrincipleTargetInfo.class, com.xray.app.router.command.PrincipleTargetInfo.Builder.class);
    }

    // Construct using com.xray.app.router.command.PrincipleTargetInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tag_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xray.app.router.command.Command.internal_static_xray_app_router_command_PrincipleTargetInfo_descriptor;
    }

    @java.lang.Override
    public com.xray.app.router.command.PrincipleTargetInfo getDefaultInstanceForType() {
      return com.xray.app.router.command.PrincipleTargetInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.xray.app.router.command.PrincipleTargetInfo build() {
      com.xray.app.router.command.PrincipleTargetInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xray.app.router.command.PrincipleTargetInfo buildPartial() {
      com.xray.app.router.command.PrincipleTargetInfo result = new com.xray.app.router.command.PrincipleTargetInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xray.app.router.command.PrincipleTargetInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        tag_.makeImmutable();
        result.tag_ = tag_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xray.app.router.command.PrincipleTargetInfo) {
        return mergeFrom((com.xray.app.router.command.PrincipleTargetInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xray.app.router.command.PrincipleTargetInfo other) {
      if (other == com.xray.app.router.command.PrincipleTargetInfo.getDefaultInstance()) return this;
      if (!other.tag_.isEmpty()) {
        if (tag_.isEmpty()) {
          tag_ = other.tag_;
          bitField0_ |= 0x00000001;
        } else {
          ensureTagIsMutable();
          tag_.addAll(other.tag_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagIsMutable();
              tag_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList tag_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagIsMutable() {
      if (!tag_.isModifiable()) {
        tag_ = new com.google.protobuf.LazyStringArrayList(tag_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @return A list containing the tag.
     */
    public com.google.protobuf.ProtocolStringList
        getTagList() {
      tag_.makeImmutable();
      return tag_;
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @return The count of tag.
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @param index The index of the element to return.
     * @return The tag at the given index.
     */
    public java.lang.String getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tag at the given index.
     */
    public com.google.protobuf.ByteString
        getTagBytes(int index) {
      return tag_.getByteString(index);
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @param index The index to set the value at.
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagIsMutable();
      tag_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @param value The tag to add.
     * @return This builder for chaining.
     */
    public Builder addTag(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagIsMutable();
      tag_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @param values The tag to add.
     * @return This builder for chaining.
     */
    public Builder addAllTag(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tag_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      tag_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tag = 1;</code>
     * @param value The bytes of the tag to add.
     * @return This builder for chaining.
     */
    public Builder addTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagIsMutable();
      tag_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.app.router.command.PrincipleTargetInfo)
  }

  // @@protoc_insertion_point(class_scope:xray.app.router.command.PrincipleTargetInfo)
  private static final com.xray.app.router.command.PrincipleTargetInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xray.app.router.command.PrincipleTargetInfo();
  }

  public static com.xray.app.router.command.PrincipleTargetInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PrincipleTargetInfo>
      PARSER = new com.google.protobuf.AbstractParser<PrincipleTargetInfo>() {
    @java.lang.Override
    public PrincipleTargetInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PrincipleTargetInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PrincipleTargetInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xray.app.router.command.PrincipleTargetInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

