// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/observatory/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.core.app.observatory.command;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.core.app.observatory.command.Config)
    com.google.protobuf.MessageOrBuilder {
}
