// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_GetStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_GetStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_Stat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_Stat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_GetStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_GetStatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_QueryStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_QueryStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_QueryStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_QueryStatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_SysStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_SysStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_SysStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_SysStatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_IpsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_IpsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_GetAllOnlineUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_GetAllOnlineUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_OnlineIPEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_OnlineIPEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_TrafficUserStat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_TrafficUserStat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_UserStat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_UserStat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_GetUsersStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_GetUsersStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_GetUsersStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_GetUsersStatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_stats_command_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_stats_command_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037app/stats/command/command.proto\022\026xray." +
      "app.stats.command\".\n\017GetStatsRequest\022\014\n\004" +
      "name\030\001 \001(\t\022\r\n\005reset\030\002 \001(\010\"#\n\004Stat\022\014\n\004nam" +
      "e\030\001 \001(\t\022\r\n\005value\030\002 \001(\003\">\n\020GetStatsRespon" +
      "se\022*\n\004stat\030\001 \001(\0132\034.xray.app.stats.comman" +
      "d.Stat\"3\n\021QueryStatsRequest\022\017\n\007pattern\030\001" +
      " \001(\t\022\r\n\005reset\030\002 \001(\010\"@\n\022QueryStatsRespons" +
      "e\022*\n\004stat\030\001 \003(\0132\034.xray.app.stats.command" +
      ".Stat\"\021\n\017SysStatsRequest\"\302\001\n\020SysStatsRes" +
      "ponse\022\024\n\014NumGoroutine\030\001 \001(\r\022\r\n\005NumGC\030\002 \001" +
      "(\r\022\r\n\005Alloc\030\003 \001(\004\022\022\n\nTotalAlloc\030\004 \001(\004\022\013\n" +
      "\003Sys\030\005 \001(\004\022\017\n\007Mallocs\030\006 \001(\004\022\r\n\005Frees\030\007 \001" +
      "(\004\022\023\n\013LiveObjects\030\010 \001(\004\022\024\n\014PauseTotalNs\030" +
      "\t \001(\004\022\016\n\006Uptime\030\n \001(\r\"\244\001\n\034GetStatsOnline" +
      "IpListResponse\022\014\n\004name\030\001 \001(\t\022J\n\003ips\030\002 \003(" +
      "\0132=.xray.app.stats.command.GetStatsOnlin" +
      "eIpListResponse.IpsEntry\032*\n\010IpsEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\003:\0028\001\"\032\n\030GetAllOn" +
      "lineUsersRequest\"*\n\031GetAllOnlineUsersRes" +
      "ponse\022\r\n\005users\030\001 \003(\t\".\n\rOnlineIPEntry\022\n\n" +
      "\002ip\030\001 \001(\t\022\021\n\tlast_seen\030\002 \001(\003\"3\n\017TrafficU" +
      "serStat\022\016\n\006uplink\030\001 \001(\003\022\020\n\010downlink\030\002 \001(" +
      "\003\"\207\001\n\010UserStat\022\r\n\005email\030\001 \001(\t\0222\n\003ips\030\002 \003" +
      "(\0132%.xray.app.stats.command.OnlineIPEntr" +
      "y\0228\n\007traffic\030\003 \001(\0132\'.xray.app.stats.comm" +
      "and.TrafficUserStat\">\n\024GetUsersStatsRequ" +
      "est\022\027\n\017include_traffic\030\001 \001(\010\022\r\n\005reset\030\002 " +
      "\001(\010\"H\n\025GetUsersStatsResponse\022/\n\005users\030\001 " +
      "\003(\0132 .xray.app.stats.command.UserStat\"\010\n" +
      "\006Config2\206\006\n\014StatsService\022_\n\010GetStats\022\'.x" +
      "ray.app.stats.command.GetStatsRequest\032(." +
      "xray.app.stats.command.GetStatsResponse\"" +
      "\000\022e\n\016GetStatsOnline\022\'.xray.app.stats.com" +
      "mand.GetStatsRequest\032(.xray.app.stats.co" +
      "mmand.GetStatsResponse\"\000\022e\n\nQueryStats\022)" +
      ".xray.app.stats.command.QueryStatsReques" +
      "t\032*.xray.app.stats.command.QueryStatsRes" +
      "ponse\"\000\022b\n\013GetSysStats\022\'.xray.app.stats." +
      "command.SysStatsRequest\032(.xray.app.stats" +
      ".command.SysStatsResponse\"\000\022w\n\024GetStatsO" +
      "nlineIpList\022\'.xray.app.stats.command.Get" +
      "StatsRequest\0324.xray.app.stats.command.Ge" +
      "tStatsOnlineIpListResponse\"\000\022z\n\021GetAllOn" +
      "lineUsers\0220.xray.app.stats.command.GetAl" +
      "lOnlineUsersRequest\0321.xray.app.stats.com" +
      "mand.GetAllOnlineUsersResponse\"\000\022n\n\rGetU" +
      "sersStats\022,.xray.app.stats.command.GetUs" +
      "ersStatsRequest\032-.xray.app.stats.command" +
      ".GetUsersStatsResponse\"\000Bd\n\032com.xray.app" +
      ".stats.commandP\001Z+github.com/xtls/xray-c" +
      "ore/app/stats/command\252\002\026Xray.App.Stats.C" +
      "ommandb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xray_app_stats_command_GetStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_app_stats_command_GetStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_GetStatsRequest_descriptor,
        new java.lang.String[] { "Name", "Reset", });
    internal_static_xray_app_stats_command_Stat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_app_stats_command_Stat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_Stat_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_xray_app_stats_command_GetStatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_xray_app_stats_command_GetStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_GetStatsResponse_descriptor,
        new java.lang.String[] { "Stat", });
    internal_static_xray_app_stats_command_QueryStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_xray_app_stats_command_QueryStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_QueryStatsRequest_descriptor,
        new java.lang.String[] { "Pattern", "Reset", });
    internal_static_xray_app_stats_command_QueryStatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_xray_app_stats_command_QueryStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_QueryStatsResponse_descriptor,
        new java.lang.String[] { "Stat", });
    internal_static_xray_app_stats_command_SysStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_xray_app_stats_command_SysStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_SysStatsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_xray_app_stats_command_SysStatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_xray_app_stats_command_SysStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_SysStatsResponse_descriptor,
        new java.lang.String[] { "NumGoroutine", "NumGC", "Alloc", "TotalAlloc", "Sys", "Mallocs", "Frees", "LiveObjects", "PauseTotalNs", "Uptime", });
    internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_descriptor,
        new java.lang.String[] { "Name", "Ips", });
    internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_IpsEntry_descriptor =
      internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_descriptor.getNestedTypes().get(0);
    internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_IpsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_GetStatsOnlineIpListResponse_IpsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_xray_app_stats_command_GetAllOnlineUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_xray_app_stats_command_GetAllOnlineUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_GetAllOnlineUsersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_xray_app_stats_command_OnlineIPEntry_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_xray_app_stats_command_OnlineIPEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_OnlineIPEntry_descriptor,
        new java.lang.String[] { "Ip", "LastSeen", });
    internal_static_xray_app_stats_command_TrafficUserStat_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_xray_app_stats_command_TrafficUserStat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_TrafficUserStat_descriptor,
        new java.lang.String[] { "Uplink", "Downlink", });
    internal_static_xray_app_stats_command_UserStat_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_xray_app_stats_command_UserStat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_UserStat_descriptor,
        new java.lang.String[] { "Email", "Ips", "Traffic", });
    internal_static_xray_app_stats_command_GetUsersStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_xray_app_stats_command_GetUsersStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_GetUsersStatsRequest_descriptor,
        new java.lang.String[] { "IncludeTraffic", "Reset", });
    internal_static_xray_app_stats_command_GetUsersStatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_xray_app_stats_command_GetUsersStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_GetUsersStatsResponse_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_xray_app_stats_command_Config_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_xray_app_stats_command_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_stats_command_Config_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
