// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

/**
 * Protobuf type {@code xray.app.stats.command.GetAllOnlineUsersResponse}
 */
public final class GetAllOnlineUsersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.app.stats.command.GetAllOnlineUsersResponse)
    GetAllOnlineUsersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllOnlineUsersResponse.newBuilder() to construct.
  private GetAllOnlineUsersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllOnlineUsersResponse() {
    users_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAllOnlineUsersResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xray.app.stats.command.GetAllOnlineUsersResponse.class, com.xray.app.stats.command.GetAllOnlineUsersResponse.Builder.class);
  }

  public static final int USERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList users_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string users = 1;</code>
   * @return A list containing the users.
   */
  public com.google.protobuf.ProtocolStringList
      getUsersList() {
    return users_;
  }
  /**
   * <code>repeated string users = 1;</code>
   * @return The count of users.
   */
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated string users = 1;</code>
   * @param index The index of the element to return.
   * @return The users at the given index.
   */
  public java.lang.String getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated string users = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the users at the given index.
   */
  public com.google.protobuf.ByteString
      getUsersBytes(int index) {
    return users_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < users_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, users_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < users_.size(); i++) {
        dataSize += computeStringSizeNoTag(users_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUsersList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xray.app.stats.command.GetAllOnlineUsersResponse)) {
      return super.equals(obj);
    }
    com.xray.app.stats.command.GetAllOnlineUsersResponse other = (com.xray.app.stats.command.GetAllOnlineUsersResponse) obj;

    if (!getUsersList()
        .equals(other.getUsersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUsersCount() > 0) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.stats.command.GetAllOnlineUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xray.app.stats.command.GetAllOnlineUsersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.app.stats.command.GetAllOnlineUsersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.app.stats.command.GetAllOnlineUsersResponse)
      com.xray.app.stats.command.GetAllOnlineUsersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xray.app.stats.command.GetAllOnlineUsersResponse.class, com.xray.app.stats.command.GetAllOnlineUsersResponse.Builder.class);
    }

    // Construct using com.xray.app.stats.command.GetAllOnlineUsersResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      users_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_GetAllOnlineUsersResponse_descriptor;
    }

    @java.lang.Override
    public com.xray.app.stats.command.GetAllOnlineUsersResponse getDefaultInstanceForType() {
      return com.xray.app.stats.command.GetAllOnlineUsersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.xray.app.stats.command.GetAllOnlineUsersResponse build() {
      com.xray.app.stats.command.GetAllOnlineUsersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xray.app.stats.command.GetAllOnlineUsersResponse buildPartial() {
      com.xray.app.stats.command.GetAllOnlineUsersResponse result = new com.xray.app.stats.command.GetAllOnlineUsersResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xray.app.stats.command.GetAllOnlineUsersResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        users_.makeImmutable();
        result.users_ = users_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xray.app.stats.command.GetAllOnlineUsersResponse) {
        return mergeFrom((com.xray.app.stats.command.GetAllOnlineUsersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xray.app.stats.command.GetAllOnlineUsersResponse other) {
      if (other == com.xray.app.stats.command.GetAllOnlineUsersResponse.getDefaultInstance()) return this;
      if (!other.users_.isEmpty()) {
        if (users_.isEmpty()) {
          users_ = other.users_;
          bitField0_ |= 0x00000001;
        } else {
          ensureUsersIsMutable();
          users_.addAll(other.users_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureUsersIsMutable();
              users_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList users_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureUsersIsMutable() {
      if (!users_.isModifiable()) {
        users_ = new com.google.protobuf.LazyStringArrayList(users_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string users = 1;</code>
     * @return A list containing the users.
     */
    public com.google.protobuf.ProtocolStringList
        getUsersList() {
      users_.makeImmutable();
      return users_;
    }
    /**
     * <code>repeated string users = 1;</code>
     * @return The count of users.
     */
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated string users = 1;</code>
     * @param index The index of the element to return.
     * @return The users at the given index.
     */
    public java.lang.String getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated string users = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the users at the given index.
     */
    public com.google.protobuf.ByteString
        getUsersBytes(int index) {
      return users_.getByteString(index);
    }
    /**
     * <code>repeated string users = 1;</code>
     * @param index The index to set the value at.
     * @param value The users to set.
     * @return This builder for chaining.
     */
    public Builder setUsers(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUsersIsMutable();
      users_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string users = 1;</code>
     * @param value The users to add.
     * @return This builder for chaining.
     */
    public Builder addUsers(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUsersIsMutable();
      users_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string users = 1;</code>
     * @param values The users to add.
     * @return This builder for chaining.
     */
    public Builder addAllUsers(
        java.lang.Iterable<java.lang.String> values) {
      ensureUsersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, users_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string users = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsers() {
      users_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string users = 1;</code>
     * @param value The bytes of the users to add.
     * @return This builder for chaining.
     */
    public Builder addUsersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureUsersIsMutable();
      users_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.app.stats.command.GetAllOnlineUsersResponse)
  }

  // @@protoc_insertion_point(class_scope:xray.app.stats.command.GetAllOnlineUsersResponse)
  private static final com.xray.app.stats.command.GetAllOnlineUsersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xray.app.stats.command.GetAllOnlineUsersResponse();
  }

  public static com.xray.app.stats.command.GetAllOnlineUsersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllOnlineUsersResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllOnlineUsersResponse>() {
    @java.lang.Override
    public GetAllOnlineUsersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAllOnlineUsersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllOnlineUsersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xray.app.stats.command.GetAllOnlineUsersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

