// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public interface GetAllOnlineUsersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.GetAllOnlineUsersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string users = 1;</code>
   * @return A list containing the users.
   */
  java.util.List<java.lang.String>
      getUsersList();
  /**
   * <code>repeated string users = 1;</code>
   * @return The count of users.
   */
  int getUsersCount();
  /**
   * <code>repeated string users = 1;</code>
   * @param index The index of the element to return.
   * @return The users at the given index.
   */
  java.lang.String getUsers(int index);
  /**
   * <code>repeated string users = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the users at the given index.
   */
  com.google.protobuf.ByteString
      getUsersBytes(int index);
}
