// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public interface GetStatsOnlineIpListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.GetStatsOnlineIpListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>map&lt;string, int64&gt; ips = 2;</code>
   */
  int getIpsCount();
  /**
   * <code>map&lt;string, int64&gt; ips = 2;</code>
   */
  boolean containsIps(
      java.lang.String key);
  /**
   * Use {@link #getIpsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getIps();
  /**
   * <code>map&lt;string, int64&gt; ips = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getIpsMap();
  /**
   * <code>map&lt;string, int64&gt; ips = 2;</code>
   */
  long getIpsOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <code>map&lt;string, int64&gt; ips = 2;</code>
   */
  long getIpsOrThrow(
      java.lang.String key);
}
