// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public interface GetUsersStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.GetUsersStatsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool include_traffic = 1;</code>
   * @return The includeTraffic.
   */
  boolean getIncludeTraffic();

  /**
   * <code>bool reset = 2;</code>
   * @return The reset.
   */
  boolean getReset();
}
