// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public interface GetUsersStatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.GetUsersStatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xray.app.stats.command.UserStat users = 1;</code>
   */
  java.util.List<com.xray.app.stats.command.UserStat> 
      getUsersList();
  /**
   * <code>repeated .xray.app.stats.command.UserStat users = 1;</code>
   */
  com.xray.app.stats.command.UserStat getUsers(int index);
  /**
   * <code>repeated .xray.app.stats.command.UserStat users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .xray.app.stats.command.UserStat users = 1;</code>
   */
  java.util.List<? extends com.xray.app.stats.command.UserStatOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .xray.app.stats.command.UserStat users = 1;</code>
   */
  com.xray.app.stats.command.UserStatOrBuilder getUsersOrBuilder(
      int index);
}
