// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public interface OnlineIPEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.OnlineIPEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int64 last_seen = 2;</code>
   * @return The lastSeen.
   */
  long getLastSeen();
}
