// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public interface SysStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.SysStatsRequest)
    com.google.protobuf.MessageOrBuilder {
}
