// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

/**
 * Protobuf type {@code xray.app.stats.command.TrafficUserStat}
 */
public final class TrafficUserStat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.app.stats.command.TrafficUserStat)
    TrafficUserStatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrafficUserStat.newBuilder() to construct.
  private TrafficUserStat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrafficUserStat() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrafficUserStat();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_TrafficUserStat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_TrafficUserStat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xray.app.stats.command.TrafficUserStat.class, com.xray.app.stats.command.TrafficUserStat.Builder.class);
  }

  public static final int UPLINK_FIELD_NUMBER = 1;
  private long uplink_ = 0L;
  /**
   * <code>int64 uplink = 1;</code>
   * @return The uplink.
   */
  @java.lang.Override
  public long getUplink() {
    return uplink_;
  }

  public static final int DOWNLINK_FIELD_NUMBER = 2;
  private long downlink_ = 0L;
  /**
   * <code>int64 downlink = 2;</code>
   * @return The downlink.
   */
  @java.lang.Override
  public long getDownlink() {
    return downlink_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uplink_ != 0L) {
      output.writeInt64(1, uplink_);
    }
    if (downlink_ != 0L) {
      output.writeInt64(2, downlink_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uplink_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uplink_);
    }
    if (downlink_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, downlink_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xray.app.stats.command.TrafficUserStat)) {
      return super.equals(obj);
    }
    com.xray.app.stats.command.TrafficUserStat other = (com.xray.app.stats.command.TrafficUserStat) obj;

    if (getUplink()
        != other.getUplink()) return false;
    if (getDownlink()
        != other.getDownlink()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UPLINK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUplink());
    hash = (37 * hash) + DOWNLINK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDownlink());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xray.app.stats.command.TrafficUserStat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xray.app.stats.command.TrafficUserStat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xray.app.stats.command.TrafficUserStat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.stats.command.TrafficUserStat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xray.app.stats.command.TrafficUserStat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.app.stats.command.TrafficUserStat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.app.stats.command.TrafficUserStat)
      com.xray.app.stats.command.TrafficUserStatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_TrafficUserStat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_TrafficUserStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xray.app.stats.command.TrafficUserStat.class, com.xray.app.stats.command.TrafficUserStat.Builder.class);
    }

    // Construct using com.xray.app.stats.command.TrafficUserStat.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uplink_ = 0L;
      downlink_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_TrafficUserStat_descriptor;
    }

    @java.lang.Override
    public com.xray.app.stats.command.TrafficUserStat getDefaultInstanceForType() {
      return com.xray.app.stats.command.TrafficUserStat.getDefaultInstance();
    }

    @java.lang.Override
    public com.xray.app.stats.command.TrafficUserStat build() {
      com.xray.app.stats.command.TrafficUserStat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xray.app.stats.command.TrafficUserStat buildPartial() {
      com.xray.app.stats.command.TrafficUserStat result = new com.xray.app.stats.command.TrafficUserStat(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xray.app.stats.command.TrafficUserStat result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uplink_ = uplink_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.downlink_ = downlink_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xray.app.stats.command.TrafficUserStat) {
        return mergeFrom((com.xray.app.stats.command.TrafficUserStat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xray.app.stats.command.TrafficUserStat other) {
      if (other == com.xray.app.stats.command.TrafficUserStat.getDefaultInstance()) return this;
      if (other.getUplink() != 0L) {
        setUplink(other.getUplink());
      }
      if (other.getDownlink() != 0L) {
        setDownlink(other.getDownlink());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              uplink_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              downlink_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long uplink_ ;
    /**
     * <code>int64 uplink = 1;</code>
     * @return The uplink.
     */
    @java.lang.Override
    public long getUplink() {
      return uplink_;
    }
    /**
     * <code>int64 uplink = 1;</code>
     * @param value The uplink to set.
     * @return This builder for chaining.
     */
    public Builder setUplink(long value) {

      uplink_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 uplink = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUplink() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uplink_ = 0L;
      onChanged();
      return this;
    }

    private long downlink_ ;
    /**
     * <code>int64 downlink = 2;</code>
     * @return The downlink.
     */
    @java.lang.Override
    public long getDownlink() {
      return downlink_;
    }
    /**
     * <code>int64 downlink = 2;</code>
     * @param value The downlink to set.
     * @return This builder for chaining.
     */
    public Builder setDownlink(long value) {

      downlink_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 downlink = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDownlink() {
      bitField0_ = (bitField0_ & ~0x00000002);
      downlink_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.app.stats.command.TrafficUserStat)
  }

  // @@protoc_insertion_point(class_scope:xray.app.stats.command.TrafficUserStat)
  private static final com.xray.app.stats.command.TrafficUserStat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xray.app.stats.command.TrafficUserStat();
  }

  public static com.xray.app.stats.command.TrafficUserStat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrafficUserStat>
      PARSER = new com.google.protobuf.AbstractParser<TrafficUserStat>() {
    @java.lang.Override
    public TrafficUserStat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TrafficUserStat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrafficUserStat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xray.app.stats.command.TrafficUserStat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

