// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public interface TrafficUserStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.TrafficUserStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uplink = 1;</code>
   * @return The uplink.
   */
  long getUplink();

  /**
   * <code>int64 downlink = 2;</code>
   * @return The downlink.
   */
  long getDownlink();
}
