// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

public interface UserStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.UserStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  java.util.List<com.xray.app.stats.command.OnlineIPEntry> 
      getIpsList();
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  com.xray.app.stats.command.OnlineIPEntry getIps(int index);
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  int getIpsCount();
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  java.util.List<? extends com.xray.app.stats.command.OnlineIPEntryOrBuilder> 
      getIpsOrBuilderList();
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  com.xray.app.stats.command.OnlineIPEntryOrBuilder getIpsOrBuilder(
      int index);

  /**
   * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
   * @return Whether the traffic field is set.
   */
  boolean hasTraffic();
  /**
   * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
   * @return The traffic.
   */
  com.xray.app.stats.command.TrafficUserStat getTraffic();
  /**
   * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
   */
  com.xray.app.stats.command.TrafficUserStatOrBuilder getTrafficOrBuilder();
}
