// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

// Protobuf Java Version: 3.25.5
package com.xray.app.stats.command;

/**
 * Protobuf type {@code xray.app.stats.command.UserStat}
 */
public final class UserStat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.app.stats.command.UserStat)
    UserStatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserStat.newBuilder() to construct.
  private UserStat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserStat() {
    email_ = "";
    ips_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserStat();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_UserStat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_UserStat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xray.app.stats.command.UserStat.class, com.xray.app.stats.command.UserStat.Builder.class);
  }

  private int bitField0_;
  public static final int EMAIL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IPS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.xray.app.stats.command.OnlineIPEntry> ips_;
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.xray.app.stats.command.OnlineIPEntry> getIpsList() {
    return ips_;
  }
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.xray.app.stats.command.OnlineIPEntryOrBuilder> 
      getIpsOrBuilderList() {
    return ips_;
  }
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  @java.lang.Override
  public int getIpsCount() {
    return ips_.size();
  }
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  @java.lang.Override
  public com.xray.app.stats.command.OnlineIPEntry getIps(int index) {
    return ips_.get(index);
  }
  /**
   * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
   */
  @java.lang.Override
  public com.xray.app.stats.command.OnlineIPEntryOrBuilder getIpsOrBuilder(
      int index) {
    return ips_.get(index);
  }

  public static final int TRAFFIC_FIELD_NUMBER = 3;
  private com.xray.app.stats.command.TrafficUserStat traffic_;
  /**
   * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
   * @return Whether the traffic field is set.
   */
  @java.lang.Override
  public boolean hasTraffic() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
   * @return The traffic.
   */
  @java.lang.Override
  public com.xray.app.stats.command.TrafficUserStat getTraffic() {
    return traffic_ == null ? com.xray.app.stats.command.TrafficUserStat.getDefaultInstance() : traffic_;
  }
  /**
   * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
   */
  @java.lang.Override
  public com.xray.app.stats.command.TrafficUserStatOrBuilder getTrafficOrBuilder() {
    return traffic_ == null ? com.xray.app.stats.command.TrafficUserStat.getDefaultInstance() : traffic_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
    }
    for (int i = 0; i < ips_.size(); i++) {
      output.writeMessage(2, ips_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getTraffic());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
    }
    for (int i = 0; i < ips_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, ips_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTraffic());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xray.app.stats.command.UserStat)) {
      return super.equals(obj);
    }
    com.xray.app.stats.command.UserStat other = (com.xray.app.stats.command.UserStat) obj;

    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getIpsList()
        .equals(other.getIpsList())) return false;
    if (hasTraffic() != other.hasTraffic()) return false;
    if (hasTraffic()) {
      if (!getTraffic()
          .equals(other.getTraffic())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (getIpsCount() > 0) {
      hash = (37 * hash) + IPS_FIELD_NUMBER;
      hash = (53 * hash) + getIpsList().hashCode();
    }
    if (hasTraffic()) {
      hash = (37 * hash) + TRAFFIC_FIELD_NUMBER;
      hash = (53 * hash) + getTraffic().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xray.app.stats.command.UserStat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xray.app.stats.command.UserStat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xray.app.stats.command.UserStat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.stats.command.UserStat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xray.app.stats.command.UserStat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.app.stats.command.UserStat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.app.stats.command.UserStat)
      com.xray.app.stats.command.UserStatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_UserStat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_UserStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xray.app.stats.command.UserStat.class, com.xray.app.stats.command.UserStat.Builder.class);
    }

    // Construct using com.xray.app.stats.command.UserStat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIpsFieldBuilder();
        getTrafficFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      email_ = "";
      if (ipsBuilder_ == null) {
        ips_ = java.util.Collections.emptyList();
      } else {
        ips_ = null;
        ipsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      traffic_ = null;
      if (trafficBuilder_ != null) {
        trafficBuilder_.dispose();
        trafficBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xray.app.stats.command.Command.internal_static_xray_app_stats_command_UserStat_descriptor;
    }

    @java.lang.Override
    public com.xray.app.stats.command.UserStat getDefaultInstanceForType() {
      return com.xray.app.stats.command.UserStat.getDefaultInstance();
    }

    @java.lang.Override
    public com.xray.app.stats.command.UserStat build() {
      com.xray.app.stats.command.UserStat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xray.app.stats.command.UserStat buildPartial() {
      com.xray.app.stats.command.UserStat result = new com.xray.app.stats.command.UserStat(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.xray.app.stats.command.UserStat result) {
      if (ipsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          ips_ = java.util.Collections.unmodifiableList(ips_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.ips_ = ips_;
      } else {
        result.ips_ = ipsBuilder_.build();
      }
    }

    private void buildPartial0(com.xray.app.stats.command.UserStat result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.email_ = email_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.traffic_ = trafficBuilder_ == null
            ? traffic_
            : trafficBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xray.app.stats.command.UserStat) {
        return mergeFrom((com.xray.app.stats.command.UserStat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xray.app.stats.command.UserStat other) {
      if (other == com.xray.app.stats.command.UserStat.getDefaultInstance()) return this;
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (ipsBuilder_ == null) {
        if (!other.ips_.isEmpty()) {
          if (ips_.isEmpty()) {
            ips_ = other.ips_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureIpsIsMutable();
            ips_.addAll(other.ips_);
          }
          onChanged();
        }
      } else {
        if (!other.ips_.isEmpty()) {
          if (ipsBuilder_.isEmpty()) {
            ipsBuilder_.dispose();
            ipsBuilder_ = null;
            ips_ = other.ips_;
            bitField0_ = (bitField0_ & ~0x00000002);
            ipsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIpsFieldBuilder() : null;
          } else {
            ipsBuilder_.addAllMessages(other.ips_);
          }
        }
      }
      if (other.hasTraffic()) {
        mergeTraffic(other.getTraffic());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.xray.app.stats.command.OnlineIPEntry m =
                  input.readMessage(
                      com.xray.app.stats.command.OnlineIPEntry.parser(),
                      extensionRegistry);
              if (ipsBuilder_ == null) {
                ensureIpsIsMutable();
                ips_.add(m);
              } else {
                ipsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getTrafficFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 1;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 1;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 1;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.xray.app.stats.command.OnlineIPEntry> ips_ =
      java.util.Collections.emptyList();
    private void ensureIpsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        ips_ = new java.util.ArrayList<com.xray.app.stats.command.OnlineIPEntry>(ips_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xray.app.stats.command.OnlineIPEntry, com.xray.app.stats.command.OnlineIPEntry.Builder, com.xray.app.stats.command.OnlineIPEntryOrBuilder> ipsBuilder_;

    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public java.util.List<com.xray.app.stats.command.OnlineIPEntry> getIpsList() {
      if (ipsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ips_);
      } else {
        return ipsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public int getIpsCount() {
      if (ipsBuilder_ == null) {
        return ips_.size();
      } else {
        return ipsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public com.xray.app.stats.command.OnlineIPEntry getIps(int index) {
      if (ipsBuilder_ == null) {
        return ips_.get(index);
      } else {
        return ipsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder setIps(
        int index, com.xray.app.stats.command.OnlineIPEntry value) {
      if (ipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpsIsMutable();
        ips_.set(index, value);
        onChanged();
      } else {
        ipsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder setIps(
        int index, com.xray.app.stats.command.OnlineIPEntry.Builder builderForValue) {
      if (ipsBuilder_ == null) {
        ensureIpsIsMutable();
        ips_.set(index, builderForValue.build());
        onChanged();
      } else {
        ipsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder addIps(com.xray.app.stats.command.OnlineIPEntry value) {
      if (ipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpsIsMutable();
        ips_.add(value);
        onChanged();
      } else {
        ipsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder addIps(
        int index, com.xray.app.stats.command.OnlineIPEntry value) {
      if (ipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIpsIsMutable();
        ips_.add(index, value);
        onChanged();
      } else {
        ipsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder addIps(
        com.xray.app.stats.command.OnlineIPEntry.Builder builderForValue) {
      if (ipsBuilder_ == null) {
        ensureIpsIsMutable();
        ips_.add(builderForValue.build());
        onChanged();
      } else {
        ipsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder addIps(
        int index, com.xray.app.stats.command.OnlineIPEntry.Builder builderForValue) {
      if (ipsBuilder_ == null) {
        ensureIpsIsMutable();
        ips_.add(index, builderForValue.build());
        onChanged();
      } else {
        ipsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder addAllIps(
        java.lang.Iterable<? extends com.xray.app.stats.command.OnlineIPEntry> values) {
      if (ipsBuilder_ == null) {
        ensureIpsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ips_);
        onChanged();
      } else {
        ipsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder clearIps() {
      if (ipsBuilder_ == null) {
        ips_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        ipsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public Builder removeIps(int index) {
      if (ipsBuilder_ == null) {
        ensureIpsIsMutable();
        ips_.remove(index);
        onChanged();
      } else {
        ipsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public com.xray.app.stats.command.OnlineIPEntry.Builder getIpsBuilder(
        int index) {
      return getIpsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public com.xray.app.stats.command.OnlineIPEntryOrBuilder getIpsOrBuilder(
        int index) {
      if (ipsBuilder_ == null) {
        return ips_.get(index);  } else {
        return ipsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public java.util.List<? extends com.xray.app.stats.command.OnlineIPEntryOrBuilder> 
         getIpsOrBuilderList() {
      if (ipsBuilder_ != null) {
        return ipsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ips_);
      }
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public com.xray.app.stats.command.OnlineIPEntry.Builder addIpsBuilder() {
      return getIpsFieldBuilder().addBuilder(
          com.xray.app.stats.command.OnlineIPEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public com.xray.app.stats.command.OnlineIPEntry.Builder addIpsBuilder(
        int index) {
      return getIpsFieldBuilder().addBuilder(
          index, com.xray.app.stats.command.OnlineIPEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    public java.util.List<com.xray.app.stats.command.OnlineIPEntry.Builder> 
         getIpsBuilderList() {
      return getIpsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xray.app.stats.command.OnlineIPEntry, com.xray.app.stats.command.OnlineIPEntry.Builder, com.xray.app.stats.command.OnlineIPEntryOrBuilder> 
        getIpsFieldBuilder() {
      if (ipsBuilder_ == null) {
        ipsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xray.app.stats.command.OnlineIPEntry, com.xray.app.stats.command.OnlineIPEntry.Builder, com.xray.app.stats.command.OnlineIPEntryOrBuilder>(
                ips_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        ips_ = null;
      }
      return ipsBuilder_;
    }

    private com.xray.app.stats.command.TrafficUserStat traffic_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.app.stats.command.TrafficUserStat, com.xray.app.stats.command.TrafficUserStat.Builder, com.xray.app.stats.command.TrafficUserStatOrBuilder> trafficBuilder_;
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     * @return Whether the traffic field is set.
     */
    public boolean hasTraffic() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     * @return The traffic.
     */
    public com.xray.app.stats.command.TrafficUserStat getTraffic() {
      if (trafficBuilder_ == null) {
        return traffic_ == null ? com.xray.app.stats.command.TrafficUserStat.getDefaultInstance() : traffic_;
      } else {
        return trafficBuilder_.getMessage();
      }
    }
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     */
    public Builder setTraffic(com.xray.app.stats.command.TrafficUserStat value) {
      if (trafficBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        traffic_ = value;
      } else {
        trafficBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     */
    public Builder setTraffic(
        com.xray.app.stats.command.TrafficUserStat.Builder builderForValue) {
      if (trafficBuilder_ == null) {
        traffic_ = builderForValue.build();
      } else {
        trafficBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     */
    public Builder mergeTraffic(com.xray.app.stats.command.TrafficUserStat value) {
      if (trafficBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          traffic_ != null &&
          traffic_ != com.xray.app.stats.command.TrafficUserStat.getDefaultInstance()) {
          getTrafficBuilder().mergeFrom(value);
        } else {
          traffic_ = value;
        }
      } else {
        trafficBuilder_.mergeFrom(value);
      }
      if (traffic_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     */
    public Builder clearTraffic() {
      bitField0_ = (bitField0_ & ~0x00000004);
      traffic_ = null;
      if (trafficBuilder_ != null) {
        trafficBuilder_.dispose();
        trafficBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     */
    public com.xray.app.stats.command.TrafficUserStat.Builder getTrafficBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTrafficFieldBuilder().getBuilder();
    }
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     */
    public com.xray.app.stats.command.TrafficUserStatOrBuilder getTrafficOrBuilder() {
      if (trafficBuilder_ != null) {
        return trafficBuilder_.getMessageOrBuilder();
      } else {
        return traffic_ == null ?
            com.xray.app.stats.command.TrafficUserStat.getDefaultInstance() : traffic_;
      }
    }
    /**
     * <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.app.stats.command.TrafficUserStat, com.xray.app.stats.command.TrafficUserStat.Builder, com.xray.app.stats.command.TrafficUserStatOrBuilder> 
        getTrafficFieldBuilder() {
      if (trafficBuilder_ == null) {
        trafficBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xray.app.stats.command.TrafficUserStat, com.xray.app.stats.command.TrafficUserStat.Builder, com.xray.app.stats.command.TrafficUserStatOrBuilder>(
                getTraffic(),
                getParentForChildren(),
                isClean());
        traffic_ = null;
      }
      return trafficBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.app.stats.command.UserStat)
  }

  // @@protoc_insertion_point(class_scope:xray.app.stats.command.UserStat)
  private static final com.xray.app.stats.command.UserStat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xray.app.stats.command.UserStat();
  }

  public static com.xray.app.stats.command.UserStat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserStat>
      PARSER = new com.google.protobuf.AbstractParser<UserStat>() {
    @java.lang.Override
    public UserStat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserStat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserStat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xray.app.stats.command.UserStat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

